### ISSUE TITLE
Problem in name

### ISSUE THREAD

**Issue by smartclash** [BerkanYildiz/UCR#1]
I have noticed that you've written the name as Ultrapowa Royale Server then how came UCR? It should be URC right?

And may i get the decrypted CSV files?

**Comment by BerkanYildiz** [comment]
You're right.

I'll post decrypted .csv as soon i have free time.

**Comment by 123456abcdef** [comment]
Just use @clanner's python script: [here](https://github.com/clugh/cocdp/blob/master/decompress_csv.py)
There is a comment on how to use it.
